language: objective-c
osx_image: xcode7.3
xcode_project: ContactsWrapper.xcworkspace
xcode_scheme: ContactsWrapperTests
xcode_sdk: iphonesimulator9.0

branches:
 only:
 - master

script:
- xcodebuild -workspace ContactsWrapper.xcworkspace -scheme ContactsWrapper -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0" clean test