language: objective-c
osx_image: xcode7.3
xcode_project: ContactsWrapper.xcworkspace
xcode_scheme: ContactsWrapperTests
xcode_sdk: iphonesimulator9.0

branches:
 only:
 - master

script: xctool -workspace 'ContactsWrapper.xcworkspace' -scheme 'ContactsWrapper' -sdk 'iphonesimulator' -configuration Debug clean test
# - xcodebuild -workspace ContactsWrapper.xcworkspace -scheme ContactsWrapper -destination "platform=iOS Simulator,name=iPhone 6,OS=9.1" clean test